#!/bin/bash
#SBATCH --time=0-0:50
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=1G
#SBATCH --account=def-yeaman


module load StdEnv/2020 samtools/1.12

samtools faidx AKXU02.1.fa


module purge
module load picard java


java -jar $EBROOTPICARD/picard.jar CreateSequenceDictionary R=AKXU02.1.fa O=AKXU02.1.dict
